#############################################################################
# Makefile for building: Ping-Pong-Classico-M2
# Generated by qmake (3.1) (Qt 5.15.1)
# Project:  ../Ping-Pong-Classico-M2/Ping-Pong-Classico-M2.pro
# Template: app
# Command: /Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/bin/qmake -o Makefile ../Ping-Pong-Classico-M2/Ping-Pong-Classico-M2.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I../Ping-Pong-Classico-M2 -I. -I/usr/local/Cellar/sdl2/2.0.12_1/include -I/Users/vilmarpavesijunior/Documents/Projetos/Ping-Pong-Classico-M2/../SDL2-2.0.9/i686-w64-mingw32/include -I/Users/vilmarpavesijunior/Documents/Projetos/Ping-Pong-Classico-M2/../SDL2_ttf-2.0.15/i686-w64-mingw32/include -I/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/macx-clang
QMAKE         = /Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Ping-Pong-Classico-M21.0.0
DISTDIR = /Users/vilmarpavesijunior/Documents/Projetos/build-Ping-Pong-Classico-M2-Desktop_Qt_5_15_1_clang_64bit-Debug/.tmp/Ping-Pong-Classico-M21.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS) -L/Users/vilmarpavesijunior/Documents/Projetos/Ping-Pong-Classico-M2/../../../../../usr/local/Cellar/sdl2/2.0.12_1/lib/ -lSDL2   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../Ping-Pong-Classico-M2/game.cpp \
		../Ping-Pong-Classico-M2/main.cpp \
		../Ping-Pong-Classico-M2/menu.cpp \
		../Ping-Pong-Classico-M2/singlePlayer.cpp \
		../Ping-Pong-Classico-M2/twoPlayers.cpp 
OBJECTS       = game.o \
		main.o \
		menu.o \
		singlePlayer.o \
		twoPlayers.o
DIST          = /Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/spec_pre.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/qdevice.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/device_config.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/unix.conf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/mac.conf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/macx.conf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/sanitize.conf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/gcc-base.conf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/clang.conf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/clang-mac.conf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/qconfig.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3d.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3drender.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/qt_functions.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/qt_config.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/spec_post.prf \
		../Ping-Pong-Classico-M2/.qmake.stash \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/toolchain.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/toolchain.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/default_pre.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/resolve_config.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/default_post.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/qml_debug.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/mac.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/warn_on.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/qmake_use.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/file_copies.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/rez.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/exceptions.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/yacc.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/lex.prf \
		../Ping-Pong-Classico-M2/Ping-Pong-Classico-M2.pro game.h \
		menu.h \
		singlePlayer.h \
		twoPlayers.h ../Ping-Pong-Classico-M2/game.cpp \
		../Ping-Pong-Classico-M2/main.cpp \
		../Ping-Pong-Classico-M2/menu.cpp \
		../Ping-Pong-Classico-M2/singlePlayer.cpp \
		../Ping-Pong-Classico-M2/twoPlayers.cpp
QMAKE_TARGET  = Ping-Pong-Classico-M2
DESTDIR       = 
TARGET        = Ping-Pong-Classico-M2

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.14.6
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/vilmarpavesijunior/Documents/Projetos/Ping-Pong-Classico-M2/Ping-Pong-Classico-M2.pro


include /Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

Ping-Pong-Classico-M2: /Users/vilmarpavesijunior/Documents/Projetos/Ping-Pong-Classico-M2/../../../../../usr/local/Cellar/sdl2/2.0.12_1/lib/libSDL2.a $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../Ping-Pong-Classico-M2/Ping-Pong-Classico-M2.pro /Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/macx-clang/qmake.conf /Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/spec_pre.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/qdevice.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/device_config.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/unix.conf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/mac.conf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/macx.conf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/sanitize.conf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/gcc-base.conf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/clang.conf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/clang-mac.conf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/qconfig.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3d.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3drender.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/qt_functions.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/qt_config.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/toolchain.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/toolchain.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/default_pre.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/resolve_config.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/default_post.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/qml_debug.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/mac.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/warn_on.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/qmake_use.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/file_copies.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/rez.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/exceptions.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/yacc.prf \
		/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/lex.prf \
		../Ping-Pong-Classico-M2/Ping-Pong-Classico-M2.pro
	$(QMAKE) -o Makefile ../Ping-Pong-Classico-M2/Ping-Pong-Classico-M2.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/spec_pre.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/qdevice.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/device_config.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/unix.conf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/mac.conf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/macx.conf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/sanitize.conf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/gcc-base.conf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/gcc-base-mac.conf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/clang.conf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/common/clang-mac.conf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/qconfig.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_core.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_help.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_location.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_network.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3d.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3drender.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_repparser.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_script.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/qt_functions.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/qt_config.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/macx-clang/qmake.conf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/exclusive_builds.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/sdk.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/toolchain.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/toolchain.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/default_pre.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/default_pre.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/resolve_config.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/default_post.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/default_post.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/objective_c.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/qml_debug.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/mac.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/warn_on.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/qmake_use.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/file_copies.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/rez.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/testcase_targets.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/exceptions.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/yacc.prf:
/Volumes/HDEXTERNO/MAC/Aplicativos/QTCreator/5.15.1/clang_64/mkspecs/features/lex.prf:
../Ping-Pong-Classico-M2/Ping-Pong-Classico-M2.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ../Ping-Pong-Classico-M2/Ping-Pong-Classico-M2.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile Ping-Pong-Classico-M2

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

check: first

benchmark: first

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

game.o: ../Ping-Pong-Classico-M2/game.cpp ../Ping-Pong-Classico-M2/game.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_main.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_stdinc.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_config.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_platform.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/begin_code.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/close_code.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_assert.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_atomic.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_audio.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_error.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_endian.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_mutex.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_thread.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_rwops.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_clipboard.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_cpuinfo.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_events.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_video.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_pixels.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_rect.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_surface.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_blendmode.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_keyboard.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_keycode.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_scancode.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_mouse.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_joystick.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_gamecontroller.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_quit.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_gesture.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_touch.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_filesystem.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_haptic.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_hints.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_loadso.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_log.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_messagebox.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_metal.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_power.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_render.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_sensor.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_shape.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_system.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_timer.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_version.h \
		../Ping-Pong-Classico-M2/menu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game.o ../Ping-Pong-Classico-M2/game.cpp

main.o: ../Ping-Pong-Classico-M2/main.cpp ../Ping-Pong-Classico-M2/twoPlayers.h \
		../Ping-Pong-Classico-M2/game.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_main.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_stdinc.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_config.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_platform.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/begin_code.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/close_code.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_assert.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_atomic.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_audio.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_error.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_endian.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_mutex.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_thread.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_rwops.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_clipboard.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_cpuinfo.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_events.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_video.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_pixels.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_rect.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_surface.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_blendmode.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_keyboard.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_keycode.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_scancode.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_mouse.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_joystick.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_gamecontroller.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_quit.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_gesture.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_touch.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_filesystem.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_haptic.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_hints.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_loadso.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_log.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_messagebox.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_metal.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_power.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_render.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_sensor.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_shape.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_system.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_timer.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_version.h \
		../Ping-Pong-Classico-M2/menu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../Ping-Pong-Classico-M2/main.cpp

menu.o: ../Ping-Pong-Classico-M2/menu.cpp ../Ping-Pong-Classico-M2/menu.h \
		../Ping-Pong-Classico-M2/game.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_main.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_stdinc.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_config.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_platform.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/begin_code.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/close_code.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_assert.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_atomic.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_audio.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_error.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_endian.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_mutex.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_thread.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_rwops.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_clipboard.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_cpuinfo.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_events.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_video.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_pixels.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_rect.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_surface.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_blendmode.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_keyboard.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_keycode.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_scancode.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_mouse.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_joystick.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_gamecontroller.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_quit.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_gesture.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_touch.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_filesystem.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_haptic.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_hints.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_loadso.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_log.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_messagebox.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_metal.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_power.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_render.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_sensor.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_shape.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_system.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_timer.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o menu.o ../Ping-Pong-Classico-M2/menu.cpp

singlePlayer.o: ../Ping-Pong-Classico-M2/singlePlayer.cpp ../Ping-Pong-Classico-M2/game.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_main.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_stdinc.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_config.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_platform.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/begin_code.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/close_code.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_assert.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_atomic.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_audio.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_error.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_endian.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_mutex.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_thread.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_rwops.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_clipboard.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_cpuinfo.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_events.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_video.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_pixels.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_rect.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_surface.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_blendmode.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_keyboard.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_keycode.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_scancode.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_mouse.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_joystick.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_gamecontroller.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_quit.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_gesture.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_touch.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_filesystem.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_haptic.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_hints.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_loadso.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_log.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_messagebox.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_metal.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_power.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_render.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_sensor.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_shape.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_system.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_timer.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o singlePlayer.o ../Ping-Pong-Classico-M2/singlePlayer.cpp

twoPlayers.o: ../Ping-Pong-Classico-M2/twoPlayers.cpp ../Ping-Pong-Classico-M2/game.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_main.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_stdinc.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_config.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_platform.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/begin_code.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/close_code.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_assert.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_atomic.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_audio.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_error.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_endian.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_mutex.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_thread.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_rwops.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_clipboard.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_cpuinfo.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_events.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_video.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_pixels.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_rect.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_surface.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_blendmode.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_keyboard.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_keycode.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_scancode.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_mouse.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_joystick.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_gamecontroller.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_quit.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_gesture.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_touch.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_filesystem.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_haptic.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_hints.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_loadso.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_log.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_messagebox.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_metal.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_power.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_render.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_sensor.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_shape.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_system.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_timer.h \
		/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2/SDL_version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o twoPlayers.o ../Ping-Pong-Classico-M2/twoPlayers.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

